features_enabled:
- energy_saving_mode
- status_reporting
- motion_detection
- remote_update
- lighting_control
- environment_monitoring
- power_monitoring
release_date: '2025-03-03'
supported_devices:
- device-0858
- device-0119
- device-0304
- device-0614
- device-0318
- device-0663
- device-0665
- device-0736
- device-0376
- device-0957
- device-0205
- device-0007
- device-0484
- device-0501
- device-0577
- device-0352
- device-0158
- device-0128
- device-0829
- device-0911
- device-0889
- device-0646
- device-0490
- device-0584
- device-0512
- device-0950
- device-0648
- device-0270
- device-0770
- device-0195
- device-0608
- device-0828
- device-0977
- device-0209
- device-0460
- device-0301
- device-0157
- device-0434
- device-0476
- device-0406
- device-0780
- device-0168
- device-0173
- device-0212
- device-0448
- device-0176
- device-0564
- device-0723
- device-0114
- device-0035
version: v2.3.1
