features_enabled:
- environment_monitoring
- energy_saving_mode
- status_reporting
- lighting_control
- power_monitoring
release_date: '2024-09-02'
supported_devices:
- device-0503
- device-0778
- device-0304
- device-0930
- device-0551
- device-0386
- device-0758
- device-0058
- device-0449
- device-0343
- device-0126
- device-0457
- device-0751
- device-0214
- device-0927
- device-0495
- device-0391
- device-0870
- device-0211
- device-0405
- device-0967
- device-0486
- device-0191
- device-0611
- device-0338
- device-0941
- device-0354
- device-0890
- device-0046
- device-0344
- device-0998
- device-0636
- device-0005
- device-0164
- device-0382
- device-0019
- device-0456
- device-0831
- device-0526
- device-0506
- device-0327
- device-0318
- device-0210
- device-0327
- device-0315
- device-0569
- device-0831
- device-0305
- device-0571
- device-0680
version: v4.2.0
