features_enabled:
- power_monitoring
- remote_update
- motion_detection
- environment_monitoring
- energy_saving_mode
- status_reporting
release_date: '2025-05-28'
supported_devices:
- device-0948
- device-0576
- device-0054
- device-0429
- device-0321
- device-0869
- device-0305
- device-0656
- device-0693
- device-0208
- device-0887
- device-0778
- device-0642
- device-0866
- device-0091
- device-0090
- device-0306
- device-0179
- device-0323
- device-0788
- device-0325
- device-0533
- device-0649
- device-0037
- device-0754
- device-0349
- device-0093
- device-0182
- device-0476
- device-0003
- device-0568
- device-0578
- device-0668
- device-0047
- device-0735
- device-0670
- device-0185
- device-0173
- device-0782
- device-0864
- device-0736
- device-0327
- device-0008
- device-0771
- device-0704
- device-0054
- device-0715
- device-0725
- device-0881
- device-0750
version: v1.0.0
